name: 'projeto_pipeline'
version: '1.0'
config-version: 2

profile: 'projeto_pipeline'

model-paths: ["models"]

models:
  projeto_pipeline:
    bronze:
      +schema: bronze
      +materialized: table

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table
seeds:
  projeto_pipeline:
    +schema: bronze
    +quote_columns: false
