projeto_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "my-gcp-dev-project-481015"
      keyfile: "C:\\Users\\eliel\\OneDrive\\Área de Trabalho\\projeto-pipeline\\gcp-key.json"
      location: "US"

      # Aqui mapeamos cada camada para um dataset diferente
      dataset: "dev_bronze"   # dbt usa este como padrão
      threads: 4
